### ISSUE TITLE
twitter icon says "unparseable json response"

### ISSUE THREAD

**Issue by cmungall** [OBOFoundry/OBOFoundry.github.io#2268] opened 2023-01-24 20:29 UTC
e.g https://obofoundry.org/ontology/uberon (but same for all others)

<img width="287" alt="image" src="https://user-images.githubusercontent.com/50745/214401444-0e86a8ef-2ece-4b48-892e-d7c3b52cfe2e.png">

perhaps to do with twitter stopping 3rd party access to their API?

Another reason to prioritize mastodon!

**Comment by nlharris** [comment] 2023-01-26 19:27
I bet it is due to Twitter no longer providing access to their API. Can we add code to not show the Twitter section of the ontology page if fetching the Twitter info fails? (which currently would mean no page would show it)

**Comment by deepakunni3** [comment] 2023-02-15 11:39
Looks like the Twitter icon is now rendering properly on ontology page for Uberon and others.

@nlharris Indeed! I think there might have been some hiccups with the Twitter API few weeks back. But looks like whatever is causing the disruption has now been resolved.

**Comment by matentzn** [comment] 2023-02-15 13:10
Instead we now get this weird thing on the ontology pages:

![image](https://user-images.githubusercontent.com/7070631/219036459-89ddea1b-9750-43a8-ae3f-cc830df4e8a2.png)

**Comment by deepakunni3** [comment] 2023-02-15 13:48
<img width="339" alt="Screenshot 2023-02-15 at 14 46 27" src="https://user-images.githubusercontent.com/4530272/219044532-7c6b3260-412d-47a6-bfca-de749df1b4e6.png">


Looks like it might be due to some issues on the img.shields.io side.

It seems sporadic at the moment. But lets keep an eye on this over the next few days to see if this is being observed persistently.

**Comment by erik-whiting** [comment] 2023-05-15 03:07
it seems like the issues here are due to errors in 3rd party libraries/APIs so I would really like to close this until it happens again. Since the problem is from a 3rd party, the only thing we can really do is put a check that says something like `if $response_from_3rd_party_api.success == false: hide_icon()`. If that's something we want to do, I think it should be in another issue specifically requesting that feature. I'll leave this issue open for a day or two if anyone objects, otherwise I'd like to close it (I'm trying to close stale issues so that they don't crowd out more actionable ones).

**Comment by erik-whiting** [comment] 2023-05-18 00:45
no feedback on my last comment so I'm going to close this

**Closed by erik-whiting** 2023-05-18 00:45 UTC
Labels: website, ontology metadata
