### ISSUE TITLE
text for principle 6 is confused about logical definitions

### ISSUE THREAD

**Issue by cmungall** [OBOFoundry/OBOFoundry.github.io#898] opened 2019-06-26 18:47 UTC
http://obofoundry.org/principles/fp-006-textual-definitions.html

This part of the page is wrong on multiple fronts:

```
Class: reproductive shoot system 
Term IRI: http://purl.obolibrary.org/obo/PO_0025082 
Definition: A shoot system (PO:0009006) in the sporophytic phase that has as part at least one sporangium (PO:0025094). 
Logical definition: subclass of: shoot system; subclass of: participates_in some reproductive shoot system development stage
```

A definition is necessary and sufficient conditions. A logical definition cannot be represented with subClassOf axioms on a named class. It should say

Logical definition: equivalentTo 'shoot system' and participates_in some 'reproductive shoot system development stage'

For it to qualify as a logical definition.

However, this is obviously not a good logical definition, as it is **completely different from the text definition**

**Comment by bpeters42** [comment] 2019-07-24 12:00
@nataled I thought we had reviewed and revised this principle? The top still states: "The original wording of this principle (given below) and content of this page is scheduled to be reviewed. Improved wording will be posted as it becomes available." I am a bit unclear which part of the Editorial working groups work is public and what is not.

**Comment by nataled** [comment] 2019-07-24 15:24
This principle was revised, but not completed. As agreed, we made public the intermediate text (since it is more descriptive than the original text), which is why that note is there. That being said, there does seem to have been some forking of updates. The text shown on the page does not fully match what we have in the running principles revision document. For example, the reproductive shoot system example is not in the original. That being said, Chris's comment about the logical definition still holds (though, again, the running principles document did not use 'subClassOf'). This will be discussed at the next EWG meeting.

**Comment by cmungall** [comment] 2019-07-25 13:30
I suggest doing the drafts as PRs rather than a separate hard to find document, will allow others e.g. technical team to provide help

**Comment by nlharris** [comment] 2021-10-05 23:23
What's the status of this? I agree with Chris that the drafts should be PRs (can be marked "draft" if they're not ready to be merged).

**Comment by nataled** [comment] 2021-10-05 23:27
Will take this up at the next EWG meeting.

**Comment by nataled** [comment] 2021-12-07 15:01
Revised on public page.

**Closed by nataled** 2021-12-07 15:01 UTC
Labels: attn: Editorial WG, principles
