### ISSUE TITLE
Status of bto

### ISSUE THREAD

**Issue by cmungall** [OBOFoundry/OBOFoundry.github.io#381] opened 2017-02-09 03:47 UTC
it's not clear we have permission to reproduce, and AFAICT there is no official OWL. This causes problems

#257
#380 

we should at least change the registry entry to have no product bto.owl

But it's not clear this should be in the registry at all if not purely open

**Comment by mcourtot** [comment] 2017-02-09 14:34
Perhaps contact Antje Chang which is the designated contact point for BTO and clarify the license? I agree that if not open we should not include it.

**Comment by cmungall** [comment] 2017-03-11 01:48
See also: https://github.com/OntoZoo/ontobee/issues/105#issuecomment-285722124

**Comment by cmungall** [comment] 2017-03-11 01:53
Note also that BTO does not parse:

```
id: BTO:0005212
name: cervical intraepithelial neoplasia cell
namespace: 
def: "Cervical intraepithelial neoplasia (CIN) is the potentially premalignant transformation and abnormal growth (dysplasia) of squamous cells on the surface of the cervix. CIN is not cancer, and is usually curable. Most cases of CIN remain stable, or are eliminated by the host's immune system without intervention. However a small percentage of cases progress to become cervical cancer, usually cervical squamous cell carcinoma (SCC), if left untreated." [Wikipedia:The_Free_Encyclopedia]
synonym: "cervical dysplasia cell" RELATED []
```

If the namespace field is specified, it cannot be blank.

**Comment by mcourtot** [comment] 2017-08-31 16:04
Hi @cmungall : any more news on this?

**Comment by mcourtot** [comment] 2017-09-28 15:53
Contacted BTO team. They fixed the OBO file - waiting on our pipelines to pick it up and provide the OWL.
Re license, Antje (the BTO contact) says "The BTO is downloadable and reproducible for free, as long as BRENDA is cited. You have the permission to transform bto.obo to bto.owl. " I'm not quite sure how to translate that in the OBO Foundry licence model - seems open with attribution, so may work?

**Comment by cmungall** [comment] 2017-09-28 16:51
https://www.brenda-enzymes.org/copy.php

"Any inclusion of BRENDA components into other data bases, or redistribution of BRENDA requires a license"

**Comment by mcourtot** [comment] 2017-10-12 09:14
@cmungall, @jamesaoverton: the PURL http://purl.obolibrary.org/obo/bto.owl still doesn't resolve. Any idea?

**Comment by cmungall** [comment] 2018-09-14 22:05
```
$ curl -vvvv -L  http://www.brenda-enzymes.info/ontology/tissue/tree/update/update_files/BrendaTissueOBO 
* Hostname was NOT found in DNS cache
*   Trying 134.169.106.60...
* Connected to www.brenda-enzymes.info (134.169.106.60) port 80 (#0)
> GET /ontology/tissue/tree/update/update_files/BrendaTissueOBO HTTP/1.1
> User-Agent: curl/7.37.1
> Host: www.brenda-enzymes.info
> Accept: */*
> 
* HTTP 1.0, assume close after body
< HTTP/1.0 403 Forbidden
< Cache-Control: no-cache
< Connection: close
< Content-Type: text/html
< 
<html><body><h1>403 Forbidden</h1>
Request forbidden by administrative rules.
</body></html>

* Closing connection 0
```

can someone try and reproduce? Not sure if this is a local issue here

**Comment by jamesaoverton** [comment] 2018-09-14 22:10
That's what I see too.

**Comment by cmungall** [comment] 2019-05-01 16:53
I still don't see any way to download the obo, without it we can't make the OWL

**Comment by cmungall** [comment] 2019-09-16 15:22
Current status update:

The URL still gives a 403:

http://www.brenda-enzymes.info/ontology/tissue/tree/update/update_files/BrendaTissueOBO

I believe it worked when I tried last week, but when it did the header no longer stated any license.

The text at the top of https://www.brenda-enzymes.org/copy.php has changed. It no longer states

> Any inclusion of BRENDA components into other data bases, or redistribution of BRENDA requires a license

It now has a less restrictive statement:

> You are granted license to copy, distribute, display and make commercial use of the BRENDA database if you make appropriate reference to BRENDA and the authors. However, if you intend to distribute a modified version, you must ask us for permission first.

So it seems we can now distribute a modified version (the OWL) if we get explicit permission (and the technical issues with the URL is fixed). However, the license of the redistributed version is still unclear, and it seems that a CC-BY-ND license would still apply.

It would be much clearer if the https://www.brenda-enzymes.org/copy.php page explicitly excluded BTO and BTO had its own separate CC-BY (or CC-0) licensing.

**Comment by alanruttenberg** [comment] 2019-09-16 21:48
What isn't clear to me is what the scope of no-derivatives is. By default I think it would be too restrictive. For instance, MIREOTing some part into another ontology would seem to be making a derivative work. Or adding axioms. I'd consider not listing BTO on the site, limiting licenses to nothing stronger than CC-BY, or perhaps they could give us a different license that makes clear that the kind of use we typically make (MIREOT, additional axioms, distribution of so-derived artifacts under CC-BY) is ok.

**Comment by nlharris** [comment] 2020-03-23 23:34
BTO is still listed.

**Comment by balhoff** [comment] 2020-03-24 00:26
The [site](https://www.brenda-enzymes.org/copy.php) specifically states CC-BY now. Also, the OBO and OWL files both resolve. It would be nice if they include reference to CC-BY directly in the OBO file header.

**Comment by matentzn** [comment] 2020-03-24 09:11
It’s already in the edit file: https://raw.githubusercontent.com/BRENDA-Enzymes/BTO/master/src/ontology/bto-edit.obo

I have contacted them for making another release. I will close this now because there are no further action items I think.

**Closed by matentzn** 2020-03-24 09:11 UTC
Labels: policy, specific ontology
