### ISSUE TITLE
Bug: Broken link in OBO Foundry Cell Ontology page

### ISSUE THREAD

**Issue by nicolevasilevsky** [OBOFoundry/OBOFoundry.github.io#1317] opened 2020-10-06 15:51 UTC
Paola reported that there is a hyperlink to the cells domain on this page but it is broken:
In the OBO Foundry Cell Ontology page, in the list on the right, the link next to "Domain" (pointing to "cells") seems broken.

Alex noted it is broken on other pages too. I'm not sure if it is actually meant to be hyperlinked?

https://github.com/obophenotype/cell-ontology/issues/772

**Comment by nicolevasilevsky** [comment] 2020-10-06 16:07
see: https://github.com/OBOFoundry/OBOFoundry.github.io/tree/master/community

**Comment by nlharris** [comment] 2020-11-16 19:52
It's either not meant to be hyperlinked, or the hyperlinks are wrong.

**Comment by nlharris** [comment] 2021-01-06 19:58
What would be the best fix for this? It sounds like it affects multiple pages, not just Cell Ontology.

**Comment by nataled** [comment] 2021-01-19 16:24
Note: this issue is basically an ontology-specific duplicate of #547 (which notes the issue is trans-ontology).

**Comment by nlharris** [comment] 2022-09-01 22:07
I agree with @nataled's observation above and suggest that we close this ticket as redundant.

**Comment by cthoyt** [comment] 2022-09-01 23:00
I actually have a fix to remove the links for the domains completely since there aren't any pages, but it's rebased on top of another PR #2076 so waiting to merge that before sending it

**Comment by nlharris** [comment] 2023-04-23 00:50
#2076 now seems to be merged

**Comment by erik-whiting** [comment] 2023-05-14 05:34
I'm going to close this specific issue because Dr. Hoyt's fix seems to fix this _specific_ problem, though #547, a related but more broad issue, remains open.

**Closed by erik-whiting** 2023-05-14 05:34 UTC
Labels: website, attn: Technical WG, volunteering-scheme
