### ISSUE TITLE
html proofer

### ISSUE THREAD

**Issue by mcourtot** [OBOFoundry/OBOFoundry.github.io#94] opened 2015-09-01 14:48 UTC
used on a random ontology html file:
- ./_site/ontology/zfs.html
  -  External link http://wiki.obofoundry.org/ failed: 403 No error
  -  anchor has no href attribute (line 1199)
  -  anchor has no href attribute (line 43)
  -  anchor has no href attribute (line 44)
  -  image http://obofoundry.org/images/foundrylogo.gif does not have an alt attribute (line 986)
  -  internal script /assets/themes/bootstrap-3/bootstrap/js/bootstrap.min.js does not exist (line 1329)
  -  internally linking to /, which does not exist (line 985)
  -  internally linking to /, which does not exist (line 1070)
  -  internally linking to /, which does not exist (line 59)
  -  internally linking to /assets/themes/bootstrap-3/bootstrap/css/bootstrap-theme.min.css, which does not exist (line 18)
  -  internally linking to /assets/themes/bootstrap-3/bootstrap/css/bootstrap.min.css, which does not exist (line 16)
  -  internally linking to /assets/themes/bootstrap-3/bootstrap/css/bs-sticky-footer.css, which does not exist (line 20)
  -  internally linking to /assets/themes/bootstrap-3/css/style.css?body=1, which does not exist (line 23)
  -  internally linking to /docs/ProjectHome.html, which does not exist (line 997)
  -  internally linking to /domain/anatomy.html, which does not exist (line 1204)
  -  internally linking to /faq/adding-custom-browsers, which does not exist (line 1095)
  -  internally linking to /faq/how-do-i-edit-metadata.html, which does not exist (line 1094)
  -  internally linking to /faq/how-do-i-register-my-ontology.html, which does not exist (line 1093)
  -  internally linking to /faq/who-is-the-foundry.html, which does not exist (line 1091)
  -  internally linking to /id-policy.html, which does not exist (line 1071)
  -  internally linking to /legacy/coordination.html, which does not exist (line 1105)
  -  internally linking to /legacy/crit.html, which does not exist (line 1107)
  -  internally linking to /legacy/literature.html, which does not exist (line 1103)
  -  internally linking to /legacy/participate.html, which does not exist (line 1104)
  -  internally linking to /legacy/relatedprojects.html, which does not exist (line 1106)
  -  internally linking to /principles/fp-000-summary.html, which does not exist (line 1009)
  -  internally linking to /principles/fp-001-open.html, which does not exist (line 1013)
  -  internally linking to /principles/fp-002-format.html, which does not exist (line 1017)
  -  internally linking to /principles/fp-003-uris.html, which does not exist (line 1021)
  -  internally linking to /principles/fp-004-versioning.html, which does not exist (line 1025)
  -  internally linking to /principles/fp-005-delineated-content.html, which does not exist (line 1029)
  -  internally linking to /principles/fp-006-textual-definitions.html, which does not exist (line 1033)
  -  internally linking to /principles/fp-007-relations.html, which does not exist (line 1037)
  -  internally linking to /principles/fp-008-documented.html, which does not exist (line 1041)
  -  internally linking to /principles/fp-009-users.html, which does not exist (line 1045)
  -  internally linking to /principles/fp-010-collaboration.html, which does not exist (line 1049)
  -  internally linking to /principles/fp-011-locus-of-authority.html, which does not exist (line 1053)
  -  internally linking to /principles/fp-012-naming-conventions.html, which does not exist (line 1057)
  -  internally linking to /principles/fp-016-maintenance.html, which does not exist (line 1061)
  -  internally linking to /publications.html, which does not exist (line 1108)
  -  internally linking to allnews.html, which does not exist (line 1080)
  -  linking to internal hash # that does not exist (line 1068)
  -  linking to internal hash # that does not exist (line 1078)
  -  linking to internal hash # that does not exist (line 1005)
  -  linking to internal hash # that does not exist (line 1088)
  -  linking to internal hash # that does not exist (line 995)
  -  linking to internal hash # that does not exist (line 1101)
    htmlproof 2.3.0 | Error:  HTML-Proofer found 47 failures!

**Comment by mcourtot** [comment] 2015-09-01 14:51
Duplicate of #85

**Comment by cmungall** [comment] 2015-09-22 00:54
I think the link checker may be reporting false positives, e.g. http://obofoundry.github.io/faq/how-do-i-edit-metadata.html exists but it says it doesn't...

**Comment by nlharris** [comment] 2020-07-28 03:51
if this is a duplicate of #85 can we close it?

**Comment by nlharris** [comment] 2020-07-28 03:51
and #103 is (i think) fixed, though not yet closed.

**Comment by nlharris** [comment] 2020-11-23 18:56
closing, duplicates #85

**Closed by nlharris** 2020-11-23 18:56 UTC
Labels: quality checks, website
