### ISSUE TITLE
Request for review of the Environment Ontology (ENVO)

### ISSUE THREAD

**Issue by pbuttigieg** [OBOFoundry/OBOFoundry.github.io#890] opened 2019-06-17 11:04 UTC
Hi all, 

I've filled out the [review form](https://docs.google.com/forms/d/e/1FAIpQLSeaxT6aqNJUxQWt26Qo7yuCGnSFgrC0DRrFzkYE4osntcM_8Q/viewform) associated with this issue template to get the ball rolling.

I noticed in the process that our release-bound URIs seem to be out of action since we updated the release process. I've put in a URL to the GitHub release/tag in the meantime, but we'll fix that soon. If you'd like to postpone the review until that's done and we have a new release out, let me know.

Looking forward to the feedback during this process.

**Comment by nataled** [comment] 2019-06-17 11:47
Thank you for your submission. The OBO Foundry Editorial Working Group, tasked with overseeing the peer review process, will begin the review at its next meeting. We hope to provide you with feedback in 4-6 weeks.

**Comment by pbuttigieg** [comment] 2019-06-18 17:06
Many thanks @nataled 

In the meantime, our version IRIs are functional (they apparently never went down, but I was using a malformed IRI).

The review version is here: http://purl.obolibrary.org/obo/envo/releases/2019-03-14/envo.owl

**Comment by nlharris** [comment] 2020-02-25 05:28
@pbuttigieg is chairing the OBO Operations Committee meeting tomorrow (2020-Feb-25). Maybe this issue can be briefly discussed.

**Comment by nlharris** [comment] 2020-03-03 23:08
(It wasn't.) @nataled are you awaiting more information from @pbuttigieg?

**Comment by nataled** [comment] 2020-03-04 17:38
@nlharris Yes, in a sense. The review was completed and the ontology found to contain some deficiencies with respect to some principles (I don't recall the details). We then asked for those to be addressed, followed by an alert to re-review when ready. We are awaiting that alert.

**Comment by wdduncan** [comment] 2020-06-09 16:47
Update:
Awaiting feedback from @pbuttigieg.
Pier reported that they are actively updating ENVO, and will get back when this round is finished.

**Comment by pbuttigieg** [comment] 2021-08-10 16:56
Greetings all - many of the issues should be fixed in the next release (several were misconfigurations or syntactic issues, while some have been addressed with support from our community and co-editors).

@nataled as discussed in today's operations call (raised by @cmungall), I'm happy to have the review process made public. Despite the long latency on our side, it may be instructive to the community.

**Comment by nlharris** [comment] 2021-08-21 21:16
I'm going to leave the "submitter action needed" tag on until the problems have been confirmed to be fixed. "Should be fixed in the next release" is good news, but we all know how sometimes those best intentions can take a while to actually come to fruition.

**Comment by ddooley** [comment] 2022-02-21 16:09
@pbuttigieg what should the action item be on this now?

**Comment by nlharris** [comment] 2023-01-06 01:05
Can this be closed?

**Comment by pfabry** [comment] 2023-03-07 19:58
Hi @pbuttigieg,
Since there has been no activity on this issue for quite a long time, we assume that it is no longer relevant and choose to close it to facilitate issues handling on this repository. Please let me know if there are any questions about this process and feel free to reopen it if you think it is still of interest.

**Closed by pfabry** 2023-03-07 19:58 UTC
Labels: attn: Editorial WG, review request, new ontology - submitter action needed
