### ISSUE TITLE
Process to change Crop for Compositional in CDNO 

### ISSUE THREAD

**Issue by LilyAndres** [OBOFoundry/OBOFoundry.github.io#1483] opened 2021-04-15 04:50 UTC
Hi OBO team. 

I have some questions. 

We are discussing an issue in CDNO [#51](https://github.com/Southern-Cross-Plant-Science/cdno/issues/51) @ddooley, @CropStoreDb, @kaiiam. It has been highlighted the need from different institutions and FoodOn members to use CDNO dietary nutritional component concentration terms for other 'material entities' and not only for crops or plants. For this reason, we are planning to change the pre-composed terms from the class `'nutritional component concentration in plant structure'` for `'nutritional component concentration in organism'` so maybe changing `'plant structure' [PO:0009011]` for `'organism' OBI:0100026`. 

With the changes described above maybe could be good to change the name of the ontology from **Crop** DNO to **Compositional** DNO. 

Would this be possible? And if so, the change from **Crop** to **Compositional** could be done by just editing the **md** **file**? Or do we need to follow a different process? 

Thanks a lot.

**Comment by jamesaoverton** [comment] 2021-04-15 12:51
That seemed to work! Sorry for the interruption, please continue.

**Comment by kaiiam** [comment] 2021-04-15 13:23
Thanks @jamesaoverton

**Comment by LilyAndres** [comment] 2021-04-26 01:36
Hey sorry we have been trying to discuss this issue; @ddooley, @CropStoreDb and I had a meeting last week. We agreed that  within terms of CDNO `'concentration of dietary nutritional component'` class, replacing `'plant structure'` with  BFO: `'material entity'` is more appropriate and generic than replacing with OBI: `'organism'`.
 
Thus:
```
'concentration of' [PATO:0000033] and inheres in some (
'dietary nutritional component' [CDNO:0000001] and
    part of some 'plant structure' [PO:0009011])
```
would become

```
'concentration of' [PATO:0000033] and inheres in some (
'dietary nutritional component' [CDNO:0000001] and
    part of some 'material_entity' [BFO:0000015])
```

Thoughts about it? @matentzn, @jamesaoverton, @kaiiam

Our justification is: CDNO `'concentration of dietary nutritional component'` terms was originally intended primarily to be associated with datasets that quantify concentration of chemical nutritional components derived from plant samples through the crop production and food supply chain. 
However, feedback, since we established the draft and published set of component terms, is that these are equally valuable for a wider range of **organismal (e.g. beefsteak)** and **non-organismal (e.g. table salt)** food materials throughout the processing and supply chain. There is no other ontology in place that provides a comprehensive set of such terms with relationships that we have established relevant to the domains (e.g. production, supply, and nutritional food composition).

In terms of use of the generic CDNO compositional terms, as outlined in the original scope, this is intended to be associated with quantification data, but also functional attributes where terms would be reused from other domains.

More generally, quantification data are widely used and reported in research literature, to inform food composition tables and labeling, or for supply chain quality assurance and control. However, the collective value is not realised due to a lack of agreed vocabularies. There is a range of major initiatives that are aiming to survey and generate new data, with which we have consulted, and this is a universal issue.

**Comment by kaiiam** [comment] 2021-04-26 07:29
@LilyAndres plan seems reasonable, but changing the axiom is a discussion internal to CDNO it doesn't need to be discussed here in the OBOFoundry github. Here we're simply asking if we can change the ontology name (**Crop** to **Compositional**) and expand the scope to nutritional terms of species beyond plants. @matentzn and @ddooley is this reasonable?

**Comment by LilyAndres** [comment] 2021-04-26 07:44
Thanks @kaiiam, I thought we were discussing the matter:

> The reason why this was not scope overlap before when you applied was that you said crop - indeed there is nothings specific enough for crops. But what about organismal traits in general? Here we have so much - OBA, VT, even phenotype ontologies.

Just wanted to make sure that if we decided to use 'material entity' it doesn't overlap as highlighted by @matentzn.

**Comment by CropStoreDb** [comment] 2021-04-26 07:53
@kaiiam,@matentzn  
As indicated by @LilyAndres and the justification therein, we are specifically requesting a change of CNDO name from 'crop' to 'compositional' and associated update in scope, in order to address requests to have this available for more generic use.

**Comment by kaiiam** [comment] 2021-04-26 07:57
@CropStoreDb and @LilyAndres fair points I just meant we should overload this issue. I think you guys nicely summed it up in the last two comments. 

@matentzn is this reasonable to proceed with?

**Comment by matentzn** [comment] 2021-04-26 08:04
I personally can't really say anything, but I have reached out to the operations committee to discuss this; sorry I forgot to add it to the last meeting, hopefully this can be dealt with via email. Will let you know ASAP!

**Comment by matentzn** [comment] 2021-04-27 09:57
Alright, there does not seem to be any official policy on changing one's ontology scopes. I think you have made your case, and the issue has been open for a while now, so I would say, go ahead with the renaming and see whether anyone screams. The steps are:
1. Make sure that the Markdown and (potentially) PURL configs have the correct information (i.e. make pull requests on these two files to change the names, and, potentially, the `domains`).
2. We leave those open for a week to see whether anyone screams, but I don't think so
3. Collaborate on potential conflicts in overlap in the future. I know you are probably aware of it, but I just want to re-iterate the principles of modularity (thanks @cmungall for bringing it up again). Many of the interoperability problems in the OBO-sphere are caused by poor modularity, e.g. cyclical dependencies between ontologies, extracting of terms from ontologies the term doesn't belong in the first place. I don't think this case here gives rise to such modularity issues, but it is good to be aware of it to understand our stake in this: being the guardians of modularity :)!

**Comment by alanruttenberg** [comment] 2021-04-27 13:04
Curious, when you say "change the pre-composed terms from the class" do you mean keeping the IRI, or deprecating the old one and creating a new term?

**Comment by kaiiam** [comment] 2021-04-27 13:11
Of course it's usually best to depreciate and replace, in this case they
are still very new (only been up for a couple months) and a work in
progress we might be able to keep the IRIs, but if that's not advisable
then we'd just replace them.

**Comment by alanruttenberg** [comment] 2021-04-27 13:18
The way I would handle it is that If there's been an official release with the older terms I would deprecate and create new. If it's just been in an unreleased development version then there's no need. If it has been released and you are sure that you know all users of the ontology and have confirmed that they can accept the change, then changing without deprecating would be fine, but in that case I would update the release to have the changes as well so that other's don't pick it up and have the wrong definition.

**Comment by kaiiam** [comment] 2021-04-27 13:20
Thanks @alanruttenberg that sounds good will do.

**Comment by LilyAndres** [comment] 2021-04-27 13:32
Great! Thank you @matentzn much appreciated and thanks @alanruttenberg we’ll proceed as suggested.

**Comment by matentzn** [comment] 2021-04-27 17:35
There is nothing more to be done here from the OBO side, so closing. Please feel free to reopen if there are questions.

**Closed by matentzn** 2021-04-27 17:35 UTC
Labels: specific ontology
