### ISSUE TITLE
need help with updating a purl

### ISSUE THREAD

**Issue by dsiegele** [OBOFoundry/OBOFoundry.github.io#132] opened 2015-10-02 06:18 UTC
We are migrating the Ontology for Microbial Phenotypes (OMP) project from SourceForge to GitHub and want to update the target URLs for the purls that are in the paper. I discovered that we can't change one of the purls because the list of maintainers doesn't include anyone on the project: 

id: /obo/omp/devel/ 
type: partial
target: http://sourceforge.net/p/microphenotypes/
maintainers: ALANRUTTENBERG,CMUNGALL,OBO

The /obo/omp/devel/ purl is connected to two purls in the paper:
http://purl.obolibrary.org/obo/omp/devel/ 
http://purl.obolibrary.org/obo/omp/devel/omp-term-request 

We need to change the target URL so that the purls direct to:
https://github.com/microbialphenotypes and https://github.com/microbialphenotypes/OMP-ontology-files/issues, respectively.

Would someone please add me as a maintainer so I can update this?  My user name is dsiegele.

Or, if I can't be added as a maintainer, would someone please update the target URL for us?

Please email me if my request is unclear or you need additional information.  d-siegele@tamu.edu

Thank you!

Debby Siegele
microbialphenotypes.org

**Comment by cmungall** [comment] 2015-10-02 06:24
OK this is very weird, I have permission to do this, but whenever I add obo-omp (your group) to the list of authorized editors it doesn't stick! Can anyone else in the obo team try?

**Comment by cmungall** [comment] 2015-10-02 06:26
Screenshot, it tells me I'm successful, yet obo-omp does not show
<img width="1130" alt="screen shot 2015-10-01 at 11 25 46 pm" src="https://cloud.githubusercontent.com/assets/50745/10240667/d296c70a-6893-11e5-9e3d-45ce3bbe83f5.png">

**Comment by cmungall** [comment] 2015-10-02 06:30
OK, well I went ahead and did this for you

/obo/omp/devel/ is now a partial redirect for https://github.com/microbialphenotypes

<img width="1162" alt="screen shot 2015-10-01 at 11 28 05 pm" src="https://cloud.githubusercontent.com/assets/50745/10240692/30894324-6894-11e5-8bc9-c7a4320d9783.png">

However, I would like to get to the stage where ontology developers like yourself are easily able to make the changes you require.

**Comment by mcourtot** [comment] 2015-10-05 18:05
I was just trying to add obo-omp to see whether I could reproduce, and it
did add me (melanie) as a maintainer (which it does by default with the
person updating the record) but it didn't add obo-omp. I was also able to
add Debbie by her username.
So it adds individual, but not groups. Interesting :)

**Comment by cmungall** [comment] 2015-10-05 21:04
OK @dsiegele you should have permission now

But this is still broken. We need to be able to add groups. We've done it in the past, and it's obviously possible, because OBO is in there. I will email the OCLC people.

**Comment by dsiegele** [comment] 2015-10-06 22:45
Chris,  I tried adding obo-omp and entering between the names of individuals and the group 'OBO'.  Now obo-omp is there, but OBO disappeared.  Maybe you can only have one group?

**Comment by dsiegele** [comment] 2015-10-06 22:45
P.S. Chris,  Thanks for all your help!  Debby

**Comment by mcourtot** [comment] 2015-10-07 08:20
Jeff from OCLC mentioned there was a problem with the SolR indexing - he is
looking into it, so hopefully things should go back to normal soon.

**Comment by cmungall** [comment] 2015-10-21 23:14
OCLC still broken as far as I can tell

**Comment by dsiegele** [comment] 2015-10-22 00:57
Since we moved OMP to github, the purl for for the issue tracker/term requests <http://purl.obolibrary.org/
obo/omp/devel/omp-term-request> directs to a 404 page not found. The purl for the development site <http://purl.obolibrary.org/obo/omp/devel/> directs to the correct page. I wonder if I have the target URL configured incorrectly.  Can someone help me figure this out?   Thank you!

The purl id is:  id: /obo/omp/devel/ 
type: partial
target: https://github.com/microbialphenotypes
maintainers: ALANRUTTENBERG,CMUNGALL,MELANIE,dsiegele,obo-omp

**Comment by cmungall** [comment] 2015-10-22 01:07
Personally I just give out the github tracker URL for issues, trying to use a purl for this buys nothing IMO.

I also notice you have two repos under https://github.com/microbialphenotypes

 * OMP-ontology-files
 * omp-term-request

It's entirely up to you how you organize things, but before you go too far my strong advice is __not to do it this way__. The advantages of using the issue tracker that is in the same repo as the thing the tracker is for is absolutely massive. (unfortunately we have not achieved this in GO which still runs the ontology from svn, but all other ontologies do it this way)

I recommend

 1. Move  OMP-ontology-files --> OMP-ontology (optional, but it's really much nicer, "files" is superflous and clunky). Note GH will take care of redirects.
 2. Remove omp-term-request, and just use the tracker in OMP-ontology
 3. (optional). Register an explicit purl /obo/omp/tracker that points to https://github.com/microbialphenotypes/OMP-ontology/issues

**Comment by dsiegele** [comment] 2015-10-26 05:21
Thank you for your feedback, Chris. The repository 'omp-term-request' was made as a test and should have been deleted right away.  Because we listed a separate purl for the issue tracker in the paper describing OMP, we are going to request an explicit purl for the tracker.

**Comment by cmungall** [comment] 2017-06-09 02:51
closing this ticket, OMP editors can make any metadata changes here:

http://obofoundry.org/ontology/omp.html

Click PURL to edit the purl, or Edit to edit metadata. Contact us if you need help!

**Closed by cmungall** 2017-06-09 02:51 UTC
Labels: OCLC
