### ISSUE TITLE
OBO Foundry site, not resolving correctly 

### ISSUE THREAD

**Issue by lschriml** [OBOFoundry/OBOFoundry.github.io#263] opened 2016-05-24 15:51 UTC
Hello, the OBO Foundry site is a list of items. 
I was editing the Principles Overview page,
creating a live link for the Issue Tracker. 

Not sure how the two are connected. 

I removed the URL from the overview text. 
Help,
Lynn

**Comment by lschriml** [comment] 2016-05-24 15:55
I got this error message in my email:
The page build completed successfully, but returned the following warning:

You are currently using the Jekyll Bootstrap framework which has a known incompatibility with Jekyll v3.1. To fix this incompatibility, change `page.theme.name` in `_includes/JB/setup` to `layout.theme.name`. Your site may not build properly until this change has been applied. For more information, see http://jekyllrb.com/docs/upgrading/2-to-3/#layout-metadata.

**Comment by jamesaoverton** [comment] 2016-05-24 16:12
I'm not quite sure about that error, so I'm going to revert today's changes and put them through a pull request instead.

**Comment by jamesaoverton** [comment] 2016-05-24 16:27
Didn't mean to close this.

@cmungall Sorry, I couldn't fix this quickly, and I have to run to a meeting now.

Reverting Lynn's changes did not fix the problem. The CSS asset paths are broken on the production site. I can't replicate this locally using `jekyll server`.

**Comment by jamesaoverton** [comment] 2016-05-24 16:29
Could be a problem with the ASSET_PATH in the templates.

**Comment by jamesaoverton** [comment] 2016-05-24 19:57
I think I fixed this with commit a708f08b684f9f64ef8a42fe4891c53651fe6b09, directly addressing the error that Lynn reported.

**Closed by jamesaoverton** 2016-05-24 19:57 UTC

**Comment by jamesaoverton** [comment] 2016-05-24 20:13
@lschriml: This problem wasn't your fault, and wasn't caused by anything that you did. GitHub updated some of the software that's used to generate the site, and broke part of our configuration. Thanks for opening an issue and including the warning you were sent.

In the process of fixing it I made a bit of a mess. Please check that the page you were editing is now in the form that you wanted: http://obofoundry.org/principles/fp-000-summary.html

**Comment by cmungall** [comment] 2016-05-25 23:35
Thanks for fixing James, apologies if this was the result of my switching the highlighter (I tested locally but as you say may not reflect in main site)

**Comment by jamesaoverton** [comment] 2016-05-26 14:41
@cmungall: It wasn't anything you did. GitHub updated the libraries they to to generate GitHub Pages, and the problem appeared the next time the site was rebuilt. Their error message was actually very helpful, but I don't use Jekyll much, so it took me a while to understand it.

**Comment by cmungall** [comment] 2016-05-26 18:37
I recently changed the _config_header.yml to use highlighter: rouge, 
could this be a cause? Can't check now

**Comment by jamesaoverton** [comment] 2016-05-26 18:42
I could be wrong, but I think it was a big global update to GitHub Pages. They must have seen the problem with Jekyll Bootstrap elsewhere and wrote a custom error message for it, that Lynn received by email as the committer. I don't think that the highlighter change caused the problem. But I don't use GitHub Pages much, so I'm not sure about any of this.

**Comment by lschriml** [comment] 2016-05-26 18:55
@jamesaoverton -- thank you for the fix !! The page looks to be in good shape.
Cheers,
Lynn
