### ISSUE TITLE
CLAO purl

### ISSUE THREAD

**Issue by luis-gonzalez-m** [OBOFoundry/OBOFoundry.github.io#1189] opened 2020-04-18 13:19 UTC
Use this form to register a new ontology with the OBO Foundry. Please read the instructions provided here:
http://obofoundry.org/docs/NewOntologyRegistrationInstructions.html

```
## Ontology title
Collembola Anatomy Ontology

## Requested ID space

CAO
## Ontology location
https://github.com/luis-gonzalez-m/Collembola

## Contact person
Name: Luis Antonio González Montaña
Email address:lagonzalezmo@unal.edu.co
GitHub username: luis-gonzalez-m

## Issue tracker
https://github.com/luis-gonzalez-m/Collembola/issues

## Ontology license

- [x] CC0 (public domain)
- [ ] CC-BY (version 3 or later)
- [ ] Other: *please specify*

## Available ontology formats
owl

## What domain is the ontology intended to cover?
Ontology-based Morphological Descriptions

## Related OBO Foundry ontologies
UBERON
HAO
TGMA

## Intended use/related projects
Standardize the anatomical terms used in morphological descriptions of taxa belonging to Collembola (Arthropoda: Hexapoda). This ontology includes terms related to internal and external anatomy.

## Data source
Taxonomical literature, Ontology repositories as ontobee.org, bioportal.org, and website www.colembola.org

## Additional comments or remarks
Some terms need new definitions and others could be proposed. Ontologies developed to describe species belongs to Collembola are under construction.   
```

**Comment by jamesaoverton** [comment] 2020-04-21 16:53
Hello @luis-gonzalez-m: What is the relation between this request and your previous prefix request #610?

**Comment by luis-gonzalez-m** [comment] 2020-04-21 17:10
Dear Dr. Overton,

Thanks for your message. I made modifications to my ontology. I submitted
it two years ago, I don't remember and received comments about the
registration process, a conflict between Sourceforget and Github. Since
then I have not received any comments until recently Darren Natale asked me
to review the ontology registration instructions again.

Thank you

Luis González

Universidad Nacional de Colombia

**Comment by jamesaoverton** [comment] 2020-04-21 17:16
Thanks @luis-gonzalez-m. I will close the previous request, and we'll go forward with this new one.

We did not handle your previous request properly. I apologize for that. Thank you for persevering!

**Comment by matentzn** [comment] 2020-05-06 07:51
Dear @luis-gonzalez-m 

Thank you for your submission. Your hierarchy looks generally reasonable, but there are a few things that currently preclude the inclusion of CAO into the OBO foundry registry.

1) You are not using OBO ids. All IDs in your ontology look something like `http://webprotege.stanford.edu/RXbjncOrHm9T4iRVcYdy3P`. Using OBO IDs is a [requirement](http://obofoundry.org/principles/fp-003-uris.html).
2) You have obviously reused many OBO ontologies, including BFO, RO, UBERON and CL, but completely removed their ids. For example:

| Label | OBO ID | Your ID |
| ----- | -------- | ------- |
| fiat object part | http://purl.obolibrary.org/obo/BFO_0000024 | http://webprotege.stanford.edu/RXbjncOrHm9T4iRVcYdy3P |
| tormogen cell | http://purl.obolibrary.org/obo/CL_0000372 | http://webprotege.stanford.edu/project/C5jwy47uikteCsueDXkxtB#tormogen_cell |
| material anatomical entity | http://purl.obolibrary.org/obo/UBERON_0000465 | http://webprotege.stanford.edu/project/C5jwy47uikteCsueDXkxtB#material_anatomical_entity |
| part of | http://purl.obolibrary.org/obo/BFO_0000050 | http://webprotege.stanford.edu/Rj5Ln9eXYL92pOVaBA1ADa |

Another big issue is the use of a bespoke `is a` relation:

http://webprotege.stanford.edu/R7xC1WmEQt1Ro6SQbJFsBu

![image](https://user-images.githubusercontent.com/7070631/81149620-37ef2d80-8f87-11ea-9ef2-5437745ebdd1.png)

This is almost certainly wrong and should be represented as SubClassOf.

 Many of your cross-references are malformed for example `CARO 0000005`. Your synonyms are sometimes lists:  for example, oral foramen has_exact_synonym:
```
mouth opening
mouth
bouche
buccal_opening
```
There also does not seem to be anything collembola-specific in your ontology (just a few links to your homepage) - no definitions, no collembola specific anatomy terms (at least as far as I can see from search).

I recommend to look at some of the other anatomy ontologies hosted here on obofoundry.org and see how they do things. At the very least, you should use the correct OBO identifiers for all your entities, from RO, UBERON, CL, BFO and anything else you have been using. We wish you good luck and look forward to your resubmission!

**Comment by luis-gonzalez-m** [comment] 2020-05-06 11:00
Dear Dr. Matentzoglu,

Thank you very much for your message. I will check my ontology.

greetings,

Luis González.

**Comment by luis-gonzalez-m** [comment] 2020-05-14 14:06
Dear Dr. Overton,


I make corrections to my ontology (use OBO id) and I want to resubmit it again.
I have doubts if the previous request should be closed to register my
Collembola Anatomy Ontology.

Thank you.

Luis González

Universidad Nacional de Colombia

**Comment by jamesaoverton** [comment] 2020-05-14 14:39
Hi @luis-gonzalez-m. Let's use this PR. We will take another look.

**Comment by luis-gonzalez-m** [comment] 2020-05-16 21:31
Dear Dr. Overton,

I have uploaded Collembola Anatomy Ontology to GitHub with required changes

Thank you 

Luis

**Comment by cmungall** [comment] 2020-05-19 16:27
@luis-gonzalez-m would you be open to using a longer prefix? We have previously had a request for CAO, for the coleoptera (beetle) ontology, they were open to using COLEO (although it looks like they never registered).

There are only so many `*AO` prefixes and we'd like to see these are fairly distributed amongst different communities rather than being purely first come first served.

**Comment by luis-gonzalez-m** [comment] 2020-05-19 21:47
Dear Dr. Mungall,

I agree with a longer prefix.

Thank you very much

Luis

**Comment by ramonawalls** [comment] 2020-05-19 22:21
@mjy Would you be willing to have a look at this ontology and provide some feedback on how it can better align with other arthropod ontologies?

**Comment by luis-gonzalez-m** [comment] 2020-05-20 00:46
Hi,
What alignment method do you employ? I have tried to align ontologies but I
have not found a method that does not remove redundant classes and can
align relation properties.

Luis

**Comment by pbuttigieg** [comment] 2020-06-02 16:28
@luis-gonzalez-m please note that @ramonawalls will help this process along

**Comment by luis-gonzalez-m** [comment] 2020-06-14 14:21
Hi,
I have a question, should I change the acronym CAO for my ontology? and not be similar with the acronym for the Coleoptera Ontology. I though in OntoColl (Ontology for Collembola), is it posssible? Thank you.

Luis

**Comment by matentzn** [comment] 2020-06-16 10:57
I think we now prefer upper cases prefixes. For your "Collembola Anatomy Ontology", these are all good possibilities:

- COLAO
- CLBAO
- CLAO
- CBAO

**Comment by luis-gonzalez-m** [comment] 2020-06-25 11:40
CLAO sounds good. I will change it in my ontology and upload again. Is it correct?

Thank you.

**Comment by matentzn** [comment] 2020-06-25 13:09
Sounds good to me!

**Comment by luis-gonzalez-m** [comment] 2020-06-30 15:18
I upload my ontology with the new acronym, CLAO.  Thank you

**Comment by matentzn** [comment] 2020-06-30 19:00
I made two more tickets on your tracker:

https://github.com/luis-gonzalez-m/Collembola/issues/1
https://github.com/luis-gonzalez-m/Collembola/issues/2

When they are closed, I will look at your ontology again! It looks like its getting there, good job!

**Comment by matentzn** [comment] 2020-08-10 10:03
@luis-gonzalez-m thank you for your great efforts to fix your ontology up! It would be great if you could add License information, title and description to your ontology file (see an example below), then you have my vote for being accepted. The OBO committee will look at your ontology again at the next meeting @ramonawalls @jamesaoverton 

Though not a requirement, but a strong encouragement: If you want to be all proper, all perfect, consider setting your release pipeline up with the [Ontology Development Kit](https://github.com/INCATools/ontology-development-kit). This will take time and care, but will be ultimately worth it. Right now, you dont distinguish between your edit file and your release file, and you will be hard pressed to update the `versionIRI` by hand all the time. Also, you dont release the OBO and JSON versions of the ontology which have become common place. But, it is not a requirement to pass I think (@ramonawalls ?).

```
<?xml version="1.0"?>
<rdf:RDF xmlns="http://purl.obolibrary.org/obo/license.owl#"
     xml:base="http://purl.obolibrary.org/obo/license.owl"
     xmlns:dc="http://purl.org/dc/elements/1.1/"
     xmlns:owl="http://www.w3.org/2002/07/owl#"
     xmlns:rdf="http://www.w3.org/1999/02/22-rdf-syntax-ns#"
     xmlns:xml="http://www.w3.org/XML/1998/namespace"
     xmlns:xsd="http://www.w3.org/2001/XMLSchema#"
     xmlns:rdfs="http://www.w3.org/2000/01/rdf-schema#"
     xmlns:terms="http://purl.org/dc/terms/">
    <owl:Ontology rdf:about="http://purl.obolibrary.org/obo/license.owl">
        <dc:description rdf:datatype="http://www.w3.org/2001/XMLSchema#string">An integrated and fictional ontology for the description of abnormal tomato phenotypes.</dc:description>
        <dc:title rdf:datatype="http://www.w3.org/2001/XMLSchema#string">Tomato Phenotype Ontology (TPO)</dc:title>
        <terms:license rdf:resource="https://creativecommons.org/publicdomain/zero/1.0/"/>
    </owl:Ontology>
    <owl:AnnotationProperty rdf:about="http://purl.org/dc/elements/1.1/description"/>
    <owl:AnnotationProperty rdf:about="http://purl.org/dc/elements/1.1/title"/>
    <owl:AnnotationProperty rdf:about="http://purl.org/dc/terms/license"/>
</rdf:RDF>
```

**Comment by luis-gonzalez-m** [comment] 2020-08-10 12:37
Hi, I will use Ontology Development Kit but I have a question, what is the difference between an edit and release file? I work on the original file, which I upload to github

**Comment by matentzn** [comment] 2020-08-10 13:15
This is what many people do:

```
clao-edit.owl # this is the file you edit.
clao.owl # this is the OWL release file that is never editted manually but generated using ROBOT with a ROBOT command (example below)
clao.obo # this is the OBO release file that is never editted manually but generated using ROBOT with a ROBOT command (example below)
```

clao.owl:
```
robot merge --input clao-edit.owl \
		reason --reasoner ELK --equivalent-classes-allowed all --exclude-tautologies structural \
		relax \
		reduce -r ELK \
		annotate --ontology-iri "http://purl.obolibrary.org/obo/clao.owl" --version-iri "http://purl.obolibrary.org/obo/clao/releases/2020-08-09/clao.owl" --output clao.owl
```

clao.obo (note, generated from clao.owl, not clao-edit.owl):
```
robot convert --input clao.owl --check false -f obo -o clao.tmp.obo && grep -v ^owl-axioms clao.tmp.obo > clao.obo && rm clao.tmp.obo.tmp.obo
```

More information about http://robot.obolibrary.org/.

Note that the Ontology Development Kit (ODK) is a bit harder to set up, but it would take away the need to manually create clao.owl and clao.obo.

**Comment by luis-gonzalez-m** [comment] 2020-08-10 18:16
I know the rules to register a new ontology and I want to increase the probabilities for it but really I need help! I'm trying to start ODK, my steps:
*Docker (ok)
*docker pull obolibrary/odkfull (ok)
*..d po -d ro -d hao -u luis-gonzalez-m -t "Collembola Anatomy Ontology" Collembola (if it is correct)
* I read instructions to push to Git and I don't understand it. Is it neccessary create a new repository? or How can I upgrade and customizing my repository?
I will check ROBOT and I hope correct the mistake between edit file and release file. It is not clear for how generate OBO  and JSON version but if you could explain me how to do this, I will. Appreciate your help.

**Comment by matentzn** [comment] 2020-08-10 21:18
Luiz, I cant help you with this right now, but perhaps a bit later this month.. If you are interested in using proper release pipelines, thats great. Your enthusiasm is great but I recommend to you to try the pure ROBOt approach I outlined above for now. The http://robot.obolibrary.org/ ROBOT documentation is extensive, and it should explain to you exactly what you need to do to get it up and running. I will try to come back to you once I have some room regarding ODK!

**Comment by luis-gonzalez-m** [comment] 2020-08-10 21:59
Great! I download robot.zip and I saved robot.bat in the same folder. Also I specified Enviromental variables in Windows 10 and I copied and pasted "icacls robot.bat /grant Users:RX /T" in powershell but it does not work.

**Comment by matentzn** [comment] 2020-08-11 19:08
Ohhh, snap... Unfortunately none of us uses Windows.. You will have to hack your way to get it to work unfortunately :( Sorry @luis-gonzalez-m. Unless @jamesaoverton has an idea who is a windows user of ROBOT and could help out?

**Comment by sbello** [comment] 2020-08-11 19:53
@luis-gonzalez-m did you try creating the robot.bat file using the alternate command rather than downloading it? I've always created the bat file rather than downloading it. Not sure it will help but I can confirm that it is possible to run ROBOT on a Windows 10 machine.

**Comment by mjy** [comment] 2020-08-11 20:05
Hi @luis-gonzalez-m Our insect-morphology group is working on similar issues righ tnow as the Coleoptera Anatomy Ontology recently has a dedicated person to help drive it's conceptual evolution, and the that effort is facing many similar technical questions that I hope to help with. 

Together with the existing HAO, and new foundational work on the Insect Anatomy Ontology I think having you "join us" would help alot with long term allignment our shared issues (regardless of wether Collembola are Insects ;)).  Our collective efforts are seeded variously, but will be under the org 'insect-morphology', here: https://github.com/insect-morphology/.   While that org is largely skeleton, we have a committed set of people to take continue steps forward.

Our group lurks at https://gitter.im/Insecta-Ontology/Lobby if you want to stop in and say hi and learn about or meeting space/schedule.

**Comment by luis-gonzalez-m** [comment] 2020-08-12 00:54
Hi @sbello and @mjy I tried both methods and Windows cannot run the robot.bat. 
I have obtained this message with icacls "Successfully processed 1 files; Failed processing 0 files" and with  echo java it returns to C:\Users\... However, I'm research what is the error and I will try it create the robot.bat following your advice. @mjy, It is a pleasure for me to participate in the Insect Anatomy Ontology project. Also I can collaborate occasionally with Lepidoptera (my previous taxonomic group) and of course with Collembola (Crustacea?). IAO will be a great ontology!!

**Comment by luis-gonzalez-m** [comment] 2020-08-13 21:20
Hi, I could not to run robo.bat. I don´t know if it is the java arguments or permissions in my laptop. However, I installed ROBOT as a Java program in Eclipse with one fail, fmt-maven-plugin, whose solution was discussed in the issue #229. I will follow the commands to evaluate my ontology. Thanks.

**Comment by matentzn** [comment] 2020-08-13 22:55
I think you might also be able to just use the robot.jar file you downloaded directly: java -jar robot.jar —info..

**Comment by luis-gonzalez-m** [comment] 2020-08-14 13:34
Hi,  ROBOT already works:

java -jar C:\Users\skipper\robot\robot.jar merge --input "C:\Users\CLAO.owl"  reason --reasoner ELK annotate --annotation-file annotations.ttl --output results/me.owl

thanks!

**Comment by luis-gonzalez-m** [comment] 2020-08-20 22:44
Hi, I am checking my ontology. Some classes have two definitions but my question is, 
when I convert the file to .obo do I upload this?

thanks

**Comment by luis-gonzalez-m** [comment] 2020-08-24 22:25
Hi, I have worked in my ontology. ROBOT generated a report and with it I corrected errors, warning, infos, and I have CLAO.obo but it was impossible for me the instructions with "src/ontology/CLAO-edit.owl". I created it with the option "create new file" but I think I made a mistake in the repository. Also, I tried to do this procedure with GitHubDesktop but I have problems with permissions. I appreciate your orientation with this.

**Comment by matentzn** [comment] 2020-08-25 12:09
Moved the discussion here: https://github.com/luis-gonzalez-m/Collembola/issues/4

**Comment by luis-gonzalez-m** [comment] 2020-09-04 15:21
Hi,
I have a bit of confusion about "database_cross_reference". I have seen different formats for this. For instance,
database_cross_reference: CARO:0000011
database_cross_reference: http://www.wikipedia.com
database_cross_reference: SPD:Ramírez
What is the format for this? and What is the difference with "dc:source"? It is not clear if "database_cross_reference" refers to database, literature source where the term was taken, author, or creator. 

Thanks

**Comment by matentzn** [comment] 2020-09-04 18:50
This ist just very confusing, and the OBO foundry should address this. There is a long standing history in the first:

```
database_cross_reference: CARO:0000011
```

This is what you use if you want to point one OBO ontology to another OBO ontology. 

I think for anything else there are no real rules. I would not have a problem with you adding a cross reference to a wikipedia article, but neither would I have a problem with you using dc:source. I would encourage you to make a new issue and ask this question here: https://github.com/information-artifact-ontology/ontology-metadata/issues

**Comment by nlharris** [comment] 2020-09-17 17:59
@matentzn would it make sense to open a new ticket for the OBO Foundry to address the database_cross_reference issue?

Other than that, what is the status of this request?

**Comment by matentzn** [comment] 2020-09-18 10:16
The discussion of xrefs has now been centralised here #1276

**Comment by matentzn** [comment] 2020-09-18 10:18
@luis-gonzalez-m As there has been a lot of back and forth on this ticket, could you let us know when you are done? I will then do a last review, present your case to the Operations Committee again to make a decision.

**Comment by luis-gonzalez-m** [comment] 2020-09-24 01:54
Hi matentzn, Well, I was reading the issue about XRefs. I think that DOI, ISBN, ORCID and citing web pages is fine. The problem are the references that are not includes in a database. In the Jonquet's paper dct:bibliographicCitation is suggested and it is intuitively clear. I will wait while a solution is proposed. Thanks

**Comment by matentzn** [comment] 2020-09-24 08:52
That is your choice! But just to be clear: this is not a breaking criteria for the review process. Especially bibliographic references. We care only that you have links to other ontologies, either using owl axioms or dbxrefs, and that’s all. The rest you can also improve over time!

**Comment by luis-gonzalez-m** [comment] 2020-09-24 20:40
Hi matentzn, the XRefs is complicated and some times to take a decision is difficult. Well, what is the following step with CLAO?

Thank you.

**Comment by matentzn** [comment] 2020-09-25 09:22
### Final review

@luis-gonzalez-m thank you for all your work to getting CLAO into shape. I did a last pass on your ontology. You are now using OBO reference ontologies throughout and stay correctly within the OBO namespace. Your ontology is consistent. At the next OBO operations meeting I will recommend you for acceptance, but OBO members can still object (so this is not yet an official acceptance). There are three general observations looking over your ontology I found important:

1) The ontology seems to have been built manually; in the long term, it makes sense to move to an ODK like system to refresh imports etc. This requires a learning curve, of course, but it keeps your ontology up to date with external ontologies.
2) The most significant problem I see with your ontology is your use of species-specific ontologies. For example, you use PLANA:nucleus part, where PLANA is an ontology focused on Planaria Flatworms. I recommend the following to you in your work over the next years. Restrict your anatomical entities to species independent ontologies such as Uberon and avoid species-specific ones such as PLANA (which is for planarian flatworms) or FMA (which is for humans). Generally, check when you map a term that it really applies to Collembola! I know this can be a daunting process, but I believe its worth it if you want your ontology to be generally reused.
3) (Minor) your bibliographic references currently use citation style "Luiz et al 2008", but should be using DOI or PMID.

**Comment by luis-gonzalez-m** [comment] 2020-10-03 22:38
Hi matentzn, 

I will follow the recommendations about the improving of clao.

Thank for your collaboration and help.

**Comment by matentzn** [comment] 2020-10-08 10:02
Hey @luis-gonzalez-m at the last OBO Operations call, your ontology was discussed and approved. We would still like to encourage you to continue improving your alignment to other OBO ontologies, especially replacing the use of species-specific references in database cross-references like PLANA with more general ontologies like Uberon. 

I took care of your metadata submission here:
https://github.com/OBOFoundry/OBOFoundry.github.io/pull/1337/files

if you want to take a look. I will merge it next week.

**Comment by luis-gonzalez-m** [comment] 2020-10-09 12:42
Hi matentzn, This is great news!! I have a doubt. When I import a new term from other ontology, I was assigned the original ID in my ontology, for example, the term "foramen" has the ID HAO:0000345. Is it correct or I need to change this ID by CLAO:00000? I will check the problem with PLANA, and clao.md.

Thank you very much!

**Comment by matentzn** [comment] 2020-10-09 13:13
I would like to close this issue here now @luis-gonzalez-m so for such questions, please make a ticket on the collembola tracker instead and tag me.

**Comment by luis-gonzalez-m** [comment] 2020-10-10 15:39
Hi matentzn, references  were replaced and checked in database_cross_reference.

**Comment by matentzn** [comment] 2020-10-11 16:58
Sounds great! I will close now :)

**Closed by matentzn** 2020-10-11 16:58 UTC
Labels: attn: Operations Committee, new ontology
