### ISSUE TITLE
NEW ONTOLOGY: Schizophrenia Ontology

### ISSUE THREAD

**Issue by phwegner** [OBOFoundry/OBOFoundry.github.io#1797] opened 2022-02-09 09:27 UTC
<a href="https://obofoundry.org/obo-nor.github.io/dashboard/scho/dashboard.html"><img src="https://img.shields.io/endpoint?url=https%3A%2F%2Fraw.githubusercontent.com%2FOBOFoundry%2Fobo-nor.github.io%2Fmaster%2Fdashboard%2Fscho%2Fdashboard-qc-badge.json" /></a>

## Ontology title
Schizophrenia Ontology

## Requested ID space
SCHO

## Ontology location
https://github.com/SCAI-BIO/schizophrenia-ontology/tree/main/releases/1.0.0

## Contact person
Name: Alpha Tom Kodamullil
Email address: alpha.tom.kodamullil@scai.fraunhofer.de
GitHub username: akodamullil

## Issue tracker
https://github.com/SCAI-BIO/schizophrenia-ontology/issues
## Version Controlled Repository
https://github.com/SCAI-BIO/schizophrenia-ontology
## Ontology license

- [ ] CC0 (public domain)
- [X] CC-BY (version 3 or later)
- [ ] Other: *please specify*

## Available ontology formats
OWL

## What domain is the ontology intended to cover?
Schizophrenia disease

## Related OBO Foundry ontologies
- mfomd 
- BFO

## Intended use/related projects
A disease ontology to classify Schizophrenia and calculate semantic similarities in the domain of Schizophrenia, Annotation of medical texts

## Data source
Several sources from domain experts assembled by Fraunhofer SCAI.

## Additional comments or remarks
Created by the team for applied semantics at Fraunhofer SCAI

## OBO Foundry pre-registration checklist

To be considered for inclusion in the OBO Foundry, an ontology must meet certain requirements, as described in in [the registration process instructions](http://obofoundry.org/docs/Policy_for_OBO_namespace_and_associated_PURL_requests.html) and the [registration review checklist](https://github.com/OBOFoundry/OBOFoundry.github.io/blob/master/docs/RegistrationChecklist.md). To ensure you are aware of some of its key points, please review the checklist below.

You can either check a box by submitted the request first and then using the GitHub interface, or replacing the `- [ ]` by `- [X]` in the following.

- [X] I have read and understood [the registration process instructions](http://obofoundry.org/docs/Policy_for_OBO_namespace_and_associated_PURL_requests.html) and the [registration checklist](https://github.com/OBOFoundry/OBOFoundry.github.io/blob/master/docs/RegistrationChecklist.md) 
- [X] There is no other ontology in the OBO Foundry which would be an appropriate place for my terms. If there was, I have contacted the editors, and we decided in mutual agreement that a separate ontology is more appropriate.
- [X] My ontology has a specific release file with a version IRI and a dc:license annotation, serialised in RDF/XML.
- [X] I understand that term definitions, while not mandatory, are key to understanding the intentions of a term especially when the ontology is used in curation. I made sure that a reasonable majority of terms in my ontology have definitions, using the [IAO:0000115](http://www.ontobee.org/ontology/IAO?iri=http://purl.obolibrary.org/obo/IAO_0000115) property.
- [X] For every term in my ontology, I checked whether another OBO Foundry ontology has one with the same meaning. If so, I re-used that term directly (not by cross-reference, by directly using the IRI).
- [X] For all relationship properties (Object and Data Property) I checked whether [RO](http://www.ontobee.org/ontology/catalog/RO?iri=http://www.w3.org/2002/07/owl%23ObjectProperty) includes an appropriate one. I understand that aligning with RO is an essential part of the overall alignment between OBO ontologies!
- [X] For the selection of appropriate annotation properties, I looked at [OMO](http://www.ontobee.org/ontology/catalog/OMO?iri=http://www.w3.org/2002/07/owl%23AnnotationProperty) first. I understand that aligning ontology metadata and term-level metadata is essential for cross-integration of OBO ontologies. 
- [X] If I was not sure about the meaning of any of the checkboxes above, I have consulted with a member of the OBO Foundry for advice.
- [X] The requested ID space does not conflict with another ID space found in other registries such as BioPortal and the Bioregistry, see [here](https://obofoundry.org/id-policy) for a complete list.

## Metadata

Please fill in the following metadata record which will be used by the OBO Foundry website. Note that the values shown are just examples, for example `yourfourletterid` could be something like `aism`, `cohm`, `mondo` (it does not have to be four letters). `your_domain_like_for_example_anatomy` could be simply `anatomy`, and the license should be whatever your actual license is. An example can be found [here](https://github.com/OBOFoundry/OBOFoundry.github.io/edit/master/ontology/amphx.md), but you really only need to fill in the metadata mentioned here.

```
id: scho
title: Schizophrenia Ontology
contact:
  email: alpha.tom.kodamullil@scai.fraunhofer.de
  label: Alpha TOm Kodamullil
description: A disease ontology for the mental disorder Schizophrenia
domain: schizophrenia
homepage: https://github.com/SCAI-BIO/schizophrenia-ontology
products:
  - id: SCHO.owl
dependencies:
  - id: BFO
tracker: https://github.com/SCAI-BIO/schizophrenia-ontology/issues
license:
  url: http://creativecommons.org/licenses/by/4.0/
  label: CC-BY
usages:
  - user: -
    description: -
```

**Comment by matentzn** [comment] 2022-02-09 10:54
Thank you @phwegner 

I will deal with this request shortly, but in the meantime, I can tell you that this:

```
 <!-- https://bio.scai.fraunhofer.de/ontology/schizophrenia#respiratory_system_disease -->

    <owl:Class rdf:about="https://bio.scai.fraunhofer.de/ontology/schizophrenia#respiratory_system_disease">
        <rdfs:subClassOf rdf:resource="http://purl.obolibrary.org/obo/DOID_7"/>
        <rdfs:label>respiratory system disease</rdfs:label>
        <Author>Abish</Author>
        <fromDOID></fromDOID>
        <importedFrom>http://purl.obolibrary.org/obo/DOID_1579</importedFrom>
        <oboInOwl1:hasDefinition>A disease of anatomical entity that located in the respiratory system which extends from the nasal sinuses to the diaphragm.</oboInOwl1:hasDefinition>
    </owl:Class>
```

Generally will not be allowed, given http://www.ontobee.org/ontology/DOID?iri=http://purl.obolibrary.org/obo/DOID_1579

Much of what we have discussed for your last submission is also still a problem here, i.e `https://bio.scai.fraunhofer.de/ontology/schizophrenia#` as an IRI prefix instead of `http://purl.obolibrary.org/obo/SCHO_`. 

Before we go in the details here we now have to insist to ensure that 

- [X] For every term in my ontology, I checked whether another OBO Foundry ontology has one with the same meaning. If so, I re-used that term directly (not by cross-reference, by directly using the IRI).

is 100% followed. This seems to be violated by the example above. Please provide some explanation on whether you have truly ensured that no term in your ontology already exists in another OBO ontology.

**Comment by lschriml** [comment] 2022-02-09 22:45
Hello @phwegner, 
   as you are using the Disease Ontology, (https://obofoundry.org/ontology/doid.html)
    it would be preferred to use our Purls rather than the Purls from OntoBee. 

Please let me know if there are disease terms that we can collaborate on. 

Cheers,
Lynn Schriml
PI of the Human Disease Ontology
lschriml@som.umaryland.edu

**Comment by phwegner** [comment] 2022-02-17 10:30
@matentzn To address your comment. We are aware that the terms are not imported in a way such that the class has the original IRI in the SCHO. But every class that is imported from somewhere else has the annotation importedFrom (http://purl.obolibrary.org/obo/DOID_1579 in your example).I fact I see the problem with that and I will discuss that with my team. Is that something the OBO Foundry could work with or should we re-import all terms so that it also has the respective IRI in the SCHO? 

The Base IRI problem is fixed! (schizophrenia -> SCHO)

**Comment by phwegner** [comment] 2022-02-17 10:36
@lschriml Sure we can change the IRIs. Where can I find the respective Purls for the Terms:

[http://purl.obolibrary.org/obo/DOID_0014667]()
[http://purl.obolibrary.org/obo/DOID_0050117]()
[http://purl.obolibrary.org/obo/DOID_104]()
[http://purl.obolibrary.org/obo/DOID_1398]()
[http://purl.obolibrary.org/obo/DOID_14566]()
[http://purl.obolibrary.org/obo/DOID_150]()
[http://purl.obolibrary.org/obo/DOID_225]()
[http://purl.obolibrary.org/obo/DOID_630]()
[http://purl.obolibrary.org/obo/DOID_7]()
[http://purl.obolibrary.org/obo/DOID_934]()

**Comment by matentzn** [comment] 2022-02-17 11:11
@phwegner thanks for looking into this:

1. all classes you import must use the correct OBO Foundry IRI - cross-references are not sufficient
1. there must not be a single term in your ontology that has the same meaning as another in all of the OBO Foundry ontologies. If you use a term representing the concept of "hand", you must use the UBERON IRI for the "hand" class directly
1. To find out which PURL to import your terms from,  search on http://www.ontobee.org/ or https://www.ebi.ac.uk/ols/index
1. You should consider using the ODK to manage your imports dynamically (see here for a [tutorial](https://oboacademy.github.io/obook/tutorial/setting-up-project-odk/)). Alternatively you can look into [ontofox](http://ontofox.hegroup.org/tutorial/import_Ontofox_output_file.php) which is easier to get started - but much harder to maintain in the long run.
1.

**Comment by phwegner** [comment] 2022-03-09 10:04
@matentzn We reworked the whole Ontology and updated it in the repo with an updated report. Please consider this as a re-submission.

**Comment by matentzn** [comment] 2022-03-10 10:39
I have not looked at the ontology again, but you know the drill by now from previous submissions: To be considered for acceptance, no dashboard checks aside from `usages` must be `red`. 

https://obofoundry.org/obo-nor.github.io/dashboard/scho/dashboard.html

Please let me know when you are done and I will re-run the checks!

**Comment by matentzn** [comment] 2022-03-23 12:12
@jannahastings Your name came up as a suggestion for reviewing this ontology from a domain expertise point of view. Would you be willing to contribute your opinion?

**Comment by jannahastings** [comment] 2022-03-23 12:33
Yes, sure. I'll take a look.

**Comment by jannahastings** [comment] 2022-04-05 16:00
I have reviewed the ontology and would like to note a few concerns. 

1.  Some of the hierarchical classifications seem a bit off with respect to how I would understand the parent classes. For example, 
- various tests are classified beneath diagnosis, but the tests themselves are not  subclasses of diagnosis, even if they are used in making diagnoses. 
- similarly, research or clinical assessment tool beneath medical intervention
- abnormal homeostasis, including e.g. hypoxia, classified beneath homeostasis. But surely hypoxia is not homeostasis? 

2. Some of the entities are not well placed with respect to BFO. For example,
- Sign from NCI thesaurus is placed outside the BFO hierarchy
- Personal attribute subsumes a mix of things with different BFO types
- 'root' from NCBI taxonomy is not an entity itself but a grouping term

3. The scope of the ontology is very broad, including many entities that are general and not specific to the domain of schizophrenia. I commend the level of re-use of content from other ontologies, but fear that nevertheless some of the added content might be better placed by contributing back to those external ontologies rather than adding as primary home in this ontology? (Also note that it would be easier to see what was going on with respect to original content vs. imported content if the imports were preserved in a module rather than all merged together. But perhaps these modules are preserved somewhere in another file, I didn't check the full repository just the one release file linked to above.)
4.

**Comment by wdduncan** [comment] 2022-04-05 16:16
Thanks @jannahastings !!!!

**Comment by phwegner** [comment] 2022-04-20 11:17
@zhengj2007 @jannahastings We are currently reviewing the reviewer's comments but had some time delays due to holidays and sickness. But we try to respond as soon as possible. Thank you for the feedback.

**Comment by BideZ** [comment] 2022-04-29 17:09
@jannahastings Thank you very much for your feedback. Sorry for the delayed response. We will try to address the first two issues mentioned above.  We will mention it in the comment when the update is pushed.

regarding the third issue: We understand your concern about the crowded usage of the entities re-used from the other external ontologies in our shizophrenia ontology. However, the primary aim of this ontology construction is to help the researchers retrieve data from research papers through text mining processes. The inclusion of ''Danio rerio' (NCBITaxon_7955), for example seems quite off from the topic, but it would make sense when mentioned in a context in a given publication (As an _in vivo_ model for studying schizophrenia, for example). We are ensuring the maximal coverage of the knowledge related to this domain so it could match our application purpose.

**Comment by wdduncan** [comment] 2022-05-09 23:07
@phwegner @BideZ I was checking up on the progress. The version of the ontology I can access is not using valid OBO IRIs.

> regarding the third issue: We understand your concern about the crowded ...

Are you saying that are wanting all the terms in the same ontology so that only one ontology can be used in NLP workflows? Sorry for not following your comment.

Aside from the IRI issue, I am noticing that you are using the `oboInOWL:hasDefinition` annotation for definitions. You should be using [IAO:0000115](https://www.ontobee.org/ontology/IAO?iri=http://purl.obolibrary.org/obo/IAO_0000115). Also, the definitions of your terms should be in genus-differentia form. For example, you define `Cambridge gamble task` as:
```
The Cambridge Gambling task (CGT) is a popular neurocognitive task used to assess impulsivity in both clinical and healthy populations. Behavioral measures of CGT include quality of decision-making, impulsivity/delay aversion, risk-taking, deliberation time, risk adjustment and overall proportion bet.
```
In genus-differentia form, the definition would be:
```
A screening method used assess impulsivity in both clinical and healthy populations.
```
The rest of information goes best in a comment. See [here](https://douroucouli.wordpress.com/2019/07/08/ontotip-write-simple-concise-clear-operational-textual-definitions/) for some tips on writing definitions.

@jannahastings already mentioned some problems with the hierarchy. So, I won't delve into those.

**Comment by BideZ** [comment] 2022-05-20 12:18
@wdduncan Thank you for the feedbacks. We are currently under discussion with our team regarding the issues that need to be addressed. We will leave a comment as soon as the the issues are resolved. Thank you very much!

**Comment by phwegner** [comment] 2022-06-10 08:04
@wdduncan To address the third comment @jannahastings : The Ontology is intended to be used for textmining and hence it makes sense to have a general set of clinical terms plus those terms that are domain specific for Schizophrenia. Thats why the scope of the Ontology seems kind of broader then it needs to be. I hope that clarifies the issue.

**Comment by BideZ** [comment] 2022-06-27 08:32
@jannahastings Sorry for the late reponse. To address the issues mentioned above:
1. Classification issues
- We have moved the tests that were originally beneath 'diagnosis' to their corresponding positions under 'planned processes'. The same holds for 'research or clinical assessment tool' according to the hierarchy provided by NCBI (https://www.ebi.ac.uk/ols/ontologies/ncit/terms?iri=http%3A%2F%2Fpurl.obolibrary.org%2Fobo%2FNCIT_C20993). 
- Last part of your comment regarding the classification problem: _abnormal homeostasis, including e.g. hypoxia, classified beneath homeostasis. But surely hypoxia is not homeostasis?_ 'Hypoxia' is an 'abnormal homeostasis' according to the reference ontology MP (https://www.ebi.ac.uk/ols/ontologies/mp/terms?iri=http%3A%2F%2Fpurl.obolibrary.org%2Fobo%2FMP_0005039) and 'abnormal homeostasis' is coming under 'homeostasis' according to the reference ontology OGMS (https://www.ebi.ac.uk/ols/ontologies/ogms/terms?iri=http%3A%2F%2Fpurl.obolibrary.org%2Fobo%2FOGMS_0000037)
2. Some entities are not properly placed:
- We have deleted 'root' from this ontology and moved 'Sign' and some terms under 'personal attribute' to their respective classes accordingly.
3. The scope is broad:
- Please see the previous comments.

We are looking forward to your reply

**Comment by BideZ** [comment] 2022-07-04 12:09
To further address the issues raised in SCHO:

- We have added the lisence for SCHO
- We have changed the ontology IRI to http://purl.obolibrary.org/obo/scho.owl, and version IRI to http://purl.obolibrary.org/obo/scho/releases/2022-06-27/scho.owl according to the [OBO Principle 4 Versioning](https://obofoundry.org/principles/fp-004-versioning.html)
- IRIs for the SCHO original terms are now changed to http://purl.obolibrary.org/obo/SCHO_XXXXXXX


> Aside from the IRI issue, I am noticing that you are using the `oboInOWL:hasDefinition` annotation for definitions. You should be using [IAO:0000115](https://www.ontobee.org/ontology/IAO?iri=http://purl.obolibrary.org/obo/IAO_0000115). 

- [IAO:0000115](https://www.ontobee.org/ontology/IAO?iri=http://purl.obolibrary.org/obo/IAO_0000115) is now used for the annotation property

> Also, the definitions of your terms should be in genus-differentia form. For example, you define `Cambridge gamble task` as:
> 
> ```
> The Cambridge Gambling task (CGT) is a popular neurocognitive task used to assess impulsivity in both clinical and healthy populations. Behavioral measures of CGT include quality of decision-making, impulsivity/delay aversion, risk-taking, deliberation time, risk adjustment and overall proportion bet.
> ```
> 
> In genus-differentia form, the definition would be:
> 
> ```
> A screening method used assess impulsivity in both clinical and healthy populations.
> ```
> 
> The rest of information goes best in a comment. See [here](https://douroucouli.wordpress.com/2019/07/08/ontotip-write-simple-concise-clear-operational-textual-definitions/) for some tips on writing definitions.

- We have changed the definitions to genus-differentia form. 

All the updates have been pushed through the latest committment. 

Thank you very much and we are looking forward to your reply.

**Comment by nlharris** [comment] 2022-07-25 20:22
@wdduncan If you have a chance to look at these responses, we can discuss this ontology during tomorrow's OFOC call.

**Comment by wdduncan** [comment] 2022-07-25 20:38
@BideZ Thanks for the replies!

> The textual definition of 'in vivo model' is 'Experimentation using a whole, living organism as opposed to a partial or dead organism.' By this definition, I would keep them under ICE.

I am unsure why you think `in vivo model` is an ICE. ICEs are information entities. They are things you can write down and/or copy from one place to another (e.g., a PDF that you can copy from one computer to another). The definition you give doesn't seem to fit this. You cannot copy an animal (in the information sense of 'copy') between locations. Although, you can copy the specifications for creating animal models between locations.

It seems more plausible that the definition refers to either 1) experimentation processes or 2) the animals that serve as the biological model for experiments.

**Comment by BideZ** [comment] 2022-07-28 11:25
@wdduncan Thank you very much for your reply. 

I agree with your statement about the definition of 'in vivo model'. 

Considering the problems from the NCIT classes, we have now removed the 'Model' class, and moved the child classes ('Biological model' with definiton: Systems designed to elucidate facts about complex biological phenomena, usually in a less complex or theoretical test environment.) to 'planned processes'. 

This would make more sense in terms of corresponding definitions to their parent classes.

We are looking forward to your replies!

**Comment by wdduncan** [comment] 2022-08-08 23:58
@BideZ Yes, I agree that a 'model' is generally a "simpler" environment than what is being model. However, it seems you are using 'model' in the physical sense (e.g., an anatomical system is a material entity) rather than the process sense. 

A knockout mouse, for instance, fits your definition. However, it is a material entity, not a planned process.

**Comment by BideZ** [comment] 2022-08-11 11:27
@wdduncan Thank you for the feedback. 

We have completely removed 'experimentation model' and moved 'in vivo model' under 'cellular organisms' and 'in vitro model' under 'material entity'. 

Furthermore, we have moved the rest terms from 'Biological Model' back to ICE, where ther terms fit more than being placed under 'planned process'

**Comment by nlharris** [comment] 2022-09-04 06:05
@wdduncan can you check whether @BideZ's changes are sufficient? Thanks!

**Comment by nlharris** [comment] 2022-09-12 22:05
@wdduncan can you take a look and get back to the ontology author? Thanks!

**Comment by wdduncan** [comment] 2022-09-20 00:21
@BideZ I am looking at ontology version:  
http://purl.obolibrary.org/obo/scho/releases/2022-06-27/scho.owl

It doesn't contain any object properties. Is this by design?

**Comment by wdduncan** [comment] 2022-09-20 00:43
@BideZ   
Questionnaire related terms, such as `Barratt impulsivity scale` and `Barron Welsh art scale` (amongst others), are incorrectly classified as planned processes. Collecting information using these questionnaires is a process, but the questionnaires themselves are information content entities.

**Comment by wdduncan** [comment] 2022-09-20 00:54
@BideZ The class `'Simple Type Schizophrenia' (http://purl.obolibrary.org/obo/NCIT_C35269)` does not have a definition. I would avoid importing such classes. Without a definition it is difficult to discern how it differs from the other Schizophrenia concepts.

**Comment by wdduncan** [comment] 2022-09-20 01:02
@BideZ The definition for `'acute schizophrenic episode' (http://purl.obolibrary.org/obo/SCHO_0000054)` sounds like it is a process:
```
Schizophrenia episode characterized by having active psychosis along with a worsening of other symptoms, such as mood problems, cognitive impairments, and negative symptoms.
```
Have you defined `Schizophrenia episode`?

**Comment by wdduncan** [comment] 2022-09-20 16:34
@BideZ  
At today's meeting, it was decided that the Schizophrenia Ontology is not ready to be accepted for the reasons pointed out in the above tickets. 

If you wish, you can address these problems and submit the ontology for consideration again. 

If you need an online portal to host your ontology, you can also put your ontology on Bioportal (https://bioportal.bioontology.org/) for the time being, and resubmit to the OBO Foundry later.

**Comment by BideZ** [comment] 2022-10-07 08:06
@wdduncan Thank you for the feedback. We will resubmit the ontology once the aforementioned issues are addressed

**Comment by addiehl** [comment] 2023-01-24 17:07
Any updates?

**Comment by matentzn** [comment] 2023-01-24 17:09
As @wdduncan points out, SCHO needs to be resubmitted when its ready, so I will close this issue here. Please open a new issue for the resubmission!

**Closed by matentzn** 2023-01-24 17:09 UTC
Labels: new ontology, new ontology - submitter action needed
